# ================================================
#                Common Settings
# ================================================

# When enabled, scrolling will only adjust run speed
# when `holdKey` is held.
HoldToAdjust = false

# The key that needs to be held to adjust movement speed.
HoldKey = "LeftAlt"

# Scroll speed sensitivity. Controls how many scrolls it
# takes to go between the minimum and maximum speed.
Steps = 5



# ================================================
#                     Other
# ================================================

# Whether or not to lock the POV while movement
# speed is being adjusted.
LockPOV = true

# Whether or not decrementing the speed while
# sprinting will toggle off sprinting.
ScrollTogglesSprintOff = true

# Resets the run speed to the maximum value when
# manually switching from "walking" to "running".
ResetSpeedOnRun = true

# Resets the run speed to the maximum value on sprint.
ResetSpeedOnSprint = true



# ================================================
#                 Game Variables
# ------------------------------------------------
# Since this mod controls some of the game's
# internal internal variables, they can no longer
# be modified externally using commands or mods.
# For that reason, I have exposed them here.
# ================================================

# Run speed multiplier.
# Game default: 3.5
MoveRunMult = 3.5

# Run speed athletics skill multiplier.
# Game default: 0.75
MoveRunAthleticsMult = 0.75

# Run speed run skill multiplier.
# Game default: 0.6
MoveSneakRunMult = 0.6
